name: Quality and Tests

# Define reusable variables
env:
  GO_VERSION: '1.24.4'
  GOLANGCI_LINT_VERSION: 'v1.64.2'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          # Keep cache disabled for linters
          cache: false

      - name: Verify Code Format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "::error::Code formatting issues found. Run 'gofmt -w .' to fix"
            gofmt -d .
            exit 1
          fi

      - name: Run Static Analysis
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --verbose --timeout=5m ./...

      - name: Security Scan
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go with Cache
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run Tests
        run: go test -v -race -timeout 10m ./...
